# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term_class',
            field=models.CharField(max_length=30),
        ),
    ]
